<?php

class HtmlHelper{
	
	public function __constructor(){
		
	}
	
	public function __destructor(){
		
	}
	
	/**
	 * Generates html email message content
	 * @param {Array} $entries - associative array with following keys acceptable
	 * ?headercolor? - background color of main header containing logo and title
	 * ?title? - title string
	 * ?subtitle? - subtitle string
	 * ?text? - main message
	 * ?note? - additional note
	 * ?website? - sent from
	 */
	public function get_email_content($entries){
		
		//TODO
		$root = dirname($_SERVER['SCRIPT_URI']) . "/..";
		
		$div = "<!DOCTYPE html PUBLIC '-//W3C//DTD XHTML 1.0 Transitional//EN' 'http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd'>"
			. "<html xmlns='http://www.w3.org/1999/xhtml'>"
    		. "<head>"
        		. "<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />"
        		. "<title>?title?</title>"
    		. "</head>"
			. "<body>"
				. "<table style='width: 100%; border-collapse: collapse; border: none;'>"
				. "<tbody>"
					. "<!-- GRID -->"
					. "<tr>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
						 . "<td style='width: 1%;'></td>"
					. "</tr>"
					. "<!-- HEADER -->"
					. "<tr style='background-color: ?headercolor?; color: white; border-bottom: 5px rgba(0,0,0,0.75) solid;'>"
						. "<td colspan='10'></td>"
						. "<td colspan='40' style='background-color: ?logocolor?; padding: 0 0 0.5%; text-align: left;'>"
							. "<img style='width:auto; height: auto; border: none;' src='" . $root . "/images/gui/logos/logo_email.png' />"
						. "</td>"
						. "<td colspan='40' style='text-align:center; padding: 2% 5%;  font-size: 2em; font-weight: 600;'>"
							. "?title?"
						. "</td>"
						. "<td colspan='10'></td>"
					. "</tr>"
					. "<!-- SEPARATOR -->"
					. "<tr style='background-color: #ccc; height: 50px;'>"
						. "<td colspan='100'></td>"
					. "</tr>"
					. "<!-- CONTENT -->"
					. "<!-- LOGO / IMG -->"
					//. "<tr style='background-color: #ccc; height: 100px;'>"
					//	. "<td colspan='10'></td>"
					//	. "<td colspan='80' style='background-color: ?logocolor?; padding: 0 0 0.5%; text-align: center;'>"
					//		. "<img style='width:auto; height: 100%;' src='' />"
					//	. "</td>"
					//	. "<td colspan='10'></td>"
					. "</tr>"
					. "<!-- SUBTITLE -->"
					. "<tr style='padding: 1% 0; background-color: #ccc; '>"
						. "<td colspan='10'></td>"
						. "<td colspan='80' style='background-color: white; padding: 2% 2% 0.5%; font-size: 1.5em; border-bottom: 1px #ccc solid;'>"
							. "?subtitle?"
						. "</td>"
						. "<td colspan='10'></td>"
					. "</tr>"
					. "<tr style='padding: 1% 0; background-color: #ccc;'>"
						. "<td colspan='10'></td>"
						. "<td colspan='80' style='background-color: white; padding: 0.5% 2% 2%; text-align: justify;'>"
							//. "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nullam congue nisi nisi, a elementum ipsum sollicitudin sit amet. Cras vulputate, enim in dapibus interdum, diam nunc sodales dolor, id congue magna eros sit amet odio. Etiam semper velit ac tempus tempus. Sed sed scelerisque augue, non mollis elit. Phasellus sit amet nisl id risus auctor interdum. Praesent non quam massa. Suspendisse ut nisl id lorem ultricies rutrum. Phasellus euismod, felis a lobortis ultrices, libero purus ornare lorem, ac ullamcorper ligula erat non mauris. Suspendisse fringilla orci neque, convallis suscipit nibh finibus vel. Suspendisse aliquet arcu sit amet ex finibus, vestibulum ullamcorper tortor ultricies. Duis at hendrerit dui."
							. "?text?"
						. "</td>"
						. "<td colspan='10'></td>"
					. "</tr>"
					. "<tr style='padding: 1% 0; background-color: #ccc;'>"
						. "<td colspan='10'></td>"
						. "<td colspan='80' style='background-color: white; padding: 0.5% 2% 2%'>"
							. "?note?"
						. "</td>"
						. "<td colspan='10'></td>"
					. "</tr>"
					. "<!-- SEPARATOR -->"
					. "<tr style='background-color: #ccc; height: 50px;'>"
						. "<td colspan='100'></td>"
					. "</tr>"
					. "<!-- FOOTER -->"
					. "<!-- SEPARATOR -->"
					. "<tr style='background-color: #aaa; height: 20px;'>"
						. "<td colspan='100'></td>"
					. "</tr>"
					. "<tr style='background-color: #aaa; text-align: center; color: #eee; border: none;'>"
						. "<td colspan='10'></td>"
						. "<td colspan='80' style='background-color: rgba(0,0,0,0.5); padding: 1% 0 0.25%; color: inherit;'>"
							. "Generated automitically from <a style='text-decoreation: none; color: inherit;'>?website?</a>"
						. "</td>"
						. "<td colspan='10'></td>"
					. "</tr>"
					. "<tr style='background-color: #aaa; text-align: center; color: #eee; border: none;'>"
						. "<td colspan='10'></td>"
						. "<td colspan='80' style='background-color: rgba(0,0,0,0.5); padding: 0 0 1%;'>"
							. "<a style='text-decoration: none; color: inherit;' href='mailto:?email?'>"
								. "Report problem"
							. "</a>"
						. "</td>"
						. "<td colspan='10'></td>"
					. "</tr>"
					. "<!-- SEPARATOR -->"
					. "<tr style='background-color: #aaa; height: 20px;'>"
						. "<td colspan='100'></td>"
					. "</tr>"
				. "</tbody>"
				. "</table>"
			. "</body>"
		. "</html>";
		
		foreach($entries as $key => $value){
			$div = str_replace($key, $value, $div);
		}
		
		return $div;
	}
	
}


?>